phrase:
  host: http://localhost:3000/api/v2
  project_id: 75a42e0199cbe6beb4c64813966caa45
  push:
    sources:
    - file: ./[locale2]/file.json
      params:
        file_format: i18next_4
        update_translations: true
        locale_id: 45ef0c0c6de320a051b282f4de18ec54
  pull:
    targets:
    - file: ./file-en.json
      params:
        file_format: i18next_4
        include_empty_translations: true
        locale_id: 45ef0c0c6de320a051b282f4de18ec54
