phrase:
  host: http://localhost:3000/api/v2
  project_id: fbbd8e2589a0fb08e4214899e17e53ca # localehost "testtest"
  # project_id: df66cb1bb3a1c33ed6a30c404e7f3690 # spaces.inc "Hello World"
  file_format: xml
  branch: "main"
  # Run `phrase push` to push en translations to Phrase
  push:
    sources:
      - file: "app/src/main/res/values-<locale_code>/strings.xml"
        params:
          update_translations: false
  pull:
    targets:
      - file: "app/src/main/res/values-<locale_code>/strings.xml"
        params:
          # optional format options for Android XML
          convert_placeholder: true
          indent_size: 2
