phrase:
  # host: http://localhost:3000/api/v2
  project_id: 600e3b4a9eed14f466ac12cbeed22a2d
  file_format: xml
  branch: "main"
  # Run `phrase push` to push en translations to Phrase
  push:
    sources:
      - file: "app/src/main/res/values/strings.xml"
        params:
          locale_id: "en"
          update_translations: false
  pull:
    targets:
      - file: "app/src/main/res/values-<locale_code>/strings.xml"
        params:
          # optional format options for Android XML
          convert_placeholder: true
          indent_size: 2
